#ifndef DASHBOARD_HPP
#define DASHBOARD_HPP

// Engine
#define BREAK "BREAK"
#define BREAK_MSGID 0x001
#define BREAK_MSGVALUE 1

#define SPEED_UP "SPEED_UP"
#define SPEED_UP_MSGID 0x005
#define SPEED_UP_MSGVALUE 1

// Headlights
#define CONTROL_HEADLIGHTS_ON "CONTROL_HEADLIGHTS_ON"
#define CONTROL_HEADLIGHTS_ON_MSGID 0x015
#define CONTROL_HEADLIGHTS_ON_MSGVALUE 1

#define CONTROL_HEADLIGHTS_OFF "CONTROL_HEADLIGHTS_OFF"
#define CONTROL_HEADLIGHTS_OFF_MSGID 0x015
#define CONTROL_HEADLIGHTS_OFF_MSGVALUE 0

// Indicator
#define CONTROL_INDICATOR_OFF_LEFT "CONTROL_INDICATOR_OFF_LEFT"
#define CONTROL_INDICATOR_OFF_LEFT_MSGID 0x019
#define CONTROL_INDICATOR_OFF_LEFT_MSGVALUE 0

#define CONTROL_INDICATOR_ON_LEFT "CONTROL_INDICATOR_ON_LEFT"
#define CONTROL_INDICATOR_ON_LEFT_MSGID 0x019
#define CONTROL_INDICATOR_ON_LEFT_MSGVALUE 1

#define CONTROL_INDICATOR_OFF_RIGHT "CONTROL_INDICATOR_OFF_RIGHT"
#define CONTROL_INDICATOR_OFF_RIGHT_MSGID 0x019
#define CONTROL_INDICATOR_OFF_RIGHT_MSGVALUE 2

#define CONTROL_INDICATOR_ON_RIGHT "CONTROL_INDICATOR_ON_RIGHT"
#define CONTROL_INDICATOR_ON_RIGHT_MSGID 0x019
#define CONTROL_INDICATOR_ON_RIGHT_MSGVALUE 3


#endif